### ISSUE TITLE
Function doesn't appear to be correctly closed off

### ISSUE THREAD

**Issue by Phoen1x84** [leeburnell/BrewdogApiExercise#1]
https://github.com/leeburnell/Work_Test/blob/34d08d10168a9a71e92e49edfbf415816938ec4e/app.js#L31

**Comment by leeburnell** [comment]
I've reviewed the code, everything looks to be closed off where applicable. Am I missing something? hmm...

**Comment by leeburnell** [comment]
Function is now closed off :)
